// Two corrections sent rapidly must reach the active worker and ledger in order.
// Failed/ambiguous delivery must reject before writing a successful reply record.
import {it,expect} from 'vitest';import {submitReply} from '../main/live-replies.mjs';
function setup(steer){const session={product:'p',child:{steer}};const s={sessions:new Map([['w',session]]),_handledAnswers:new Set(),_answerKey:i=>i.answer,_saveState(){}};return {s,session};}
it('serializes provider acceptance and recording, without duplicates',async()=>{const seen=[];let release;const {s}=setup(async text=>{seen.push('send '+text);if(text==='one')await new Promise(r=>release=r);});const send=answer=>submitReply(s,{product:'p',id:'w',answer},()=>{seen.push('save '+answer);return {answer};});const a=send('one'),b=send('two');await new Promise(r=>setImmediate(r));expect(seen).toEqual(['send one','send two']);release();await Promise.all([a,b]);expect(seen).toEqual(['send one','send two','save one','save two']);expect(s._handledAnswers.size).toBe(2);});
it('keeps a failed send out of the ledger and allows a later retry',async()=>{const {s}=setup(async()=>{throw Error('disconnected');});let writes=0;await expect(submitReply(s,{product:'p',id:'w',answer:'x'},()=>writes++)).rejects.toThrow('disconnected');expect(writes).toBe(0);});
it('does not steer a different product or a withdrawn reply',async()=>{let sent=0;const {s}=setup(async()=>sent++);await submitReply(s,{product:'other',id:'w',answer:'x'},()=>({answer:'x'}));await submitReply(s,{product:'p',id:'w',answer:'(withdrawn)'},()=>({answer:'(withdrawn)'}));expect(sent).toBe(0);});
it('refuses permission overrides on a running turn',async()=>{let sent=0;const {s}=setup(async()=>sent++);await expect(submitReply(s,{product:'p',id:'w',answer:'x',permissionMode:'bypassPermissions'},()=>({}))).rejects.toThrow();expect(sent).toBe(0);});
it('releases accepted input when the worker fails between ack and recording',async()=>{const {s,session}=setup(async()=>{session.exitFailed=true;});const calls=[];s.redeliverAnswer=i=>calls.push(i.answer);s.deliverMidflightReply=()=>calls.push('retry');await submitReply(s,{product:'p',id:'w',answer:'last correction'},()=>({answer:'last correction'}));expect(calls).toEqual(['last correction','retry']);});
it('does not retry a correction after a successful completed turn',async()=>{const {s,session}=setup(async()=>{session.exitFailed=false;});s.redeliverAnswer=()=>{throw Error('duplicate');};await submitReply(s,{product:'p',id:'w',answer:'x'},()=>({answer:'x'}));expect(s._handledAnswers.has('x')).toBe(true);});
it('records the task identity when the store returns an undecorated ledger item',async()=>{const {s}=setup(async()=>{});s._answerKey=i=>`${i.product}:${i.id}:${i.answer}`;await submitReply(s,{product:'p',id:'w',answer:'once'},()=>({id:'w',answer:'once'}));expect(s._handledAnswers.has('p:w:once')).toBe(true);});
it('accepts the reply composer default null permission choice without changing the active grants',async()=>{let sent=0;const {s}=setup(async()=>sent++);await submitReply(s,{product:'p',id:'w',answer:'x',permissionMode:null},()=>({answer:'x'}));expect(sent).toBe(1);});
it('releases an interrupted correction without restarting a task the user stopped',async()=>{const {s,session}=setup(async()=>{session.exitFailed=true;session.stoppedByUs=true;});let released=0;s.redeliverAnswer=()=>released++;s.deliverMidflightReply=()=>{throw Error('Stop must stay stopped');};await submitReply(s,{product:'p',id:'w',answer:'x'},()=>({answer:'x'}));expect(released).toBe(1);});
it('distinguishes accepted provider input from a failed local save',async()=>{const {s}=setup(async()=>{});await expect(submitReply(s,{product:'p',id:'w',answer:'x'},()=>{throw Error('disk full');})).rejects.toThrow('received this message');});
