// Approved MP-06: /rc is a task operation, never run as model prose.
// Codex and near-match names must not silently inherit Claude remote access.
// w-79bffd7ec3 replaced the confirmation card: a user could type /rc, walk away
// and find it had stopped at a card asking again. Typing it now turns remote
// control on, or off when it is already on, with nothing left to press.
import {it,expect} from 'vitest';
import {providerCommand} from '../shared/provider-commands.mjs';
import {remoteSessionUrl,taskRemoteControl} from '../main/task-remote-control.mjs';
import {taskCommand} from '../main/task-commands.mjs';
it('routes only the exact Claude command and alias locally',()=>{for(const word of ['/remote-control','/rc'])expect(providerCommand(word,'claude').route).toBe('remote');expect(providerCommand('/rc','codex').route).toBe('unavailable');expect(providerCommand('/rc-extra','claude').route).toBe('unavailable');});
it('accepts only a provider session link',()=>{expect(remoteSessionUrl('https://claude.ai/code/session_123')).toBe('https://claude.ai/code/session_123');for(const url of ['https://claude.ai.evil/code/session_123','javascript:alert(1)','https://user@claude.ai/code/session_123','https://claude.ai/code/session_123?next=evil'])expect(remoteSessionUrl(url)).toBe(null);});
it('refuses Codex before creating a bridge',async()=>{const sup={store:{readItem:()=>({id:'x'})},_engineFor:()=> 'codex'};await expect(taskRemoteControl(sup,'p','x','enable')).rejects.toThrow('Claude Code');});
import {EventEmitter} from 'node:events';
function harness(){const child=new EventEmitter();const requests=[];child.stdin={writable:true,end(){this.writable=false;}};child.holdInput=()=>{};child.control=async request=>{requests.push(request);return request.enabled?{session_url:'https://claude.ai/code/session_123',bridge_epoch:2}:{};};const session={product:'p',child,remoteIdle:true};return {session,requests,sup:{store:{readItem:()=>({id:'x',title:'task'}),listProducts:()=>[{slug:'p'}]},sessions:new Map([['x',session]]),_engineFor:()=> 'claude',isPersonal:()=>false,rowSessionFor:()=>({sessionId:'saved'})}};}
it('enables and disables the owned process without launching another',async()=>{const {sup,requests,session}=harness();expect((await taskRemoteControl(sup,'p','x','enable')).state).toBe('ready');expect(requests.map(r=>r.subtype)).toEqual(['initialize','remote_control']);expect(session.remoteHeld).toBe(true);expect((await taskRemoteControl(sup,'p','x','disable')).state).toBe('off');expect(session.remoteHeld).toBe(false);});
it('clears the live link when the process exits',async()=>{const {sup,session}=harness();await taskRemoteControl(sup,'p','x','enable');session.child.emit('exit',1);expect((await taskRemoteControl(sup,'p','x')).url).toBeUndefined();});
it('keeps a stop action if disable cannot be confirmed',async()=>{const {sup,session}=harness();await taskRemoteControl(sup,'p','x','enable');session.child.control=async()=>{throw Error('Disconnected')};const value=await taskRemoteControl(sup,'p','x','disable');expect(value.state).toBe('failed');expect(value.mayBeActive).toBe(true);expect(session.remoteHeld).toBe(true);});
it('rejects stale provider status from an earlier bridge epoch',async()=>{const {sup,session}=harness();await taskRemoteControl(sup,'p','x','enable');session.child.emit('bridge-state',{state:'failed',bridge_epoch:1});expect((await taskRemoteControl(sup,'p','x')).state).toBe('ready');session.child.emit('bridge-state',{state:'reconnecting',bridge_epoch:2});expect((await taskRemoteControl(sup,'p','x')).state).toBe('reconnecting');});
it('one toggle turns it on with no confirmation, the next turns it off',async()=>{const {sup,requests,session}=harness();expect((await taskRemoteControl(sup,'p','x','toggle')).state).toBe('ready');expect(requests.map(r=>r.subtype)).toEqual(['initialize','remote_control']);expect(session.remoteHeld).toBe(true);expect((await taskRemoteControl(sup,'p','x','toggle')).state).toBe('off');expect(session.remoteHeld).toBe(false);expect((await taskRemoteControl(sup,'p','x','toggle')).state).toBe('ready');});
it('a toggle while it is still connecting does not start a second one',async()=>{const {sup,requests}=harness();sup._remoteControls=new Map([[JSON.stringify(['p','x']),{state:'connecting'}]]);expect((await taskRemoteControl(sup,'p','x','toggle')).state).toBe('connecting');expect(requests).toEqual([]);});
it('a toggle after a failure that may still be live turns it off rather than on',async()=>{const {sup,session}=harness();session.remoteHeld=true;sup._remoteControls=new Map([[JSON.stringify(['p','x']),{state:'failed',mayBeActive:true}]]);expect((await taskRemoteControl(sup,'p','x','toggle')).state).toBe('off');});
it('the typed command hands back the composer at once and turns it on',async()=>{const {sup,requests}=harness();Object.assign(sup,{_saveState(){},remoteControl:(p,id,a)=>taskRemoteControl(sup,p,id,a)});const value=await taskCommand(sup,'p','x','/rc');expect(value.state).toBe('done');await new Promise(r=>setTimeout(r,0));expect(requests.map(r=>r.subtype)).toEqual(['initialize','remote_control']);expect((await taskRemoteControl(sup,'p','x')).state).toBe('ready');});
it('dismisses a failed attempt that has no active bridge',async()=>{const {sup}=harness();sup._remoteControls=new Map([[JSON.stringify(['p','x']),{state:'failed',mayBeActive:false}]]);expect((await taskRemoteControl(sup,'p','x','dismiss')).state).toBe('off');});
