import { providerCommands } from '../shared/provider-commands.mjs';
// "/" MEANS TWO THINGS NOW, AND THIS FILE IS THE GUARD ON BOTH.
//
// Of three ways of answering that, the one picked: keep the six modes at the
// top and add only the commands that say something about how a message runs,
// which are /model, /effort, /fast, /goal, /context, /usage, /mcp and
// /compact. They are read out of the installed binary at build time rather
// than typed into a file, so the list cannot rot quietly.
//
// THE THREE THINGS THAT CAN GO WRONG, ONE SECTION EACH:
//
//   1. The list stops being read and starts being typed, which is the exact
//      thing the design rules out, and it fails silently the day Claude Code
//      renames a command.
//   2. The menu starts lying: offering these on a row that does not reach Claude
//      Code, or letting a mode row and a command row be told apart only by
//      pressing one. The first half is its own file since the second engine came
//      back: tests/the-slash-menu-offers-nothing-codex-cannot-run.test.mjs.
//   3. A brief gets skipped by accident, which is a worker that does not know
//      which row it is on.
//
// THE MEASUREMENT UNDER ALL OF IT, taken 2026-08-27 against the installed
// 2.1.246, because the obvious design does not work and nothing here makes
// sense without it. A prompt of `/context`, a blank line, and a real question
// returned the context table and NOTHING ELSE: 142 lines, zero mentions of the
// question. A command eats whatever is attached to it. That is why a command is
// a message of its own rather than a modifier on the user's.

import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { Supervisor } from '../main/supervisor.mjs';
import {
  CLAUDE_COMMANDS, READ_FROM, commandDraft, commandHint, commandMatches,
  commandPrompt, commandWords,
} from '../shared/claude-commands.mjs';
import { WANTED, commandFrom, moduleText } from '../scripts/read-claude-commands.mjs';
import { slashRows, rowKey, rowSays } from '../renderer/src/slash-menu.ts';
import { MODE_HINT, MODE_ORDER } from '../renderer/src/modes.ts';

const root = path.join(path.dirname(fileURLToPath(import.meta.url)), '..');
const read = (p) => fs.readFileSync(path.join(root, p), 'utf8');

describe('the eight are hers, and they are read rather than typed', () => {
  it('is exactly the eight she named, in her order', () => {
    // The chosen eight, in the chosen order: /model, /effort, /fast, /goal,
    // /context, /usage, /mcp, /compact. Nothing added, nothing reordered,
    // nothing dropped. This is the one list in the pipeline that is a
    // judgement, and that judgement was the accepted cost of picking this option.
    expect(WANTED.slice(0, 8)).toEqual(['model', 'effort', 'fast', 'goal', 'context', 'usage', 'mcp', 'compact']);
    expect(CLAUDE_COMMANDS.map((c) => c.name)).toEqual(expect.arrayContaining(WANTED));
  });

  it('carries the version it was read from, so a stale list is visible', () => {
    // Not a formality. Four versions of Claude Code landed on this Mac in the
    // four days to 26 August; without a version on the file, a list read a
    // month ago and a list read this morning look identical.
    expect(READ_FROM).toMatch(/^\d+\.\d+\.\d+$/);
  });

  it('is generated, and says so, and is not to be edited by hand', () => {
    const generated = read('shared/claude-commands.generated.mjs');
    expect(generated).toContain('GENERATED BY scripts/read-claude-commands.mjs');
    expect(generated).toContain('DO NOT EDIT BY HAND');
  });

  it('is regenerated by the build rather than by somebody remembering to', () => {
    // A script nobody runs rots exactly as quietly as a file nobody edits.
    const pkg = JSON.parse(read('package.json'));
    expect(pkg.scripts.build).toContain('node scripts/read-claude-commands.mjs');
  });

  it('has nobody typing one of these sentences into a source file', () => {
    // The failure this is aimed at is somebody "fixing" a description by
    // editing our copy of it. Every sentence has to come from the generated
    // table; the only place a command's own words may be written by hand is the
    // generated file itself.
    for (const file of ['renderer/src/slash-menu.ts', 'renderer/src/components/Focus.tsx', 'shared/claude-commands.mjs']) {
      const text = read(file);
      for (const cmd of CLAUDE_COMMANDS) expect(text).not.toContain(cmd.description);
    }
  });

  it('reads the description out of a real record, escapes and all', () => {
    // The record shape, verbatim out of 2.1.246. `—` is the em dash in
    // /goal's own description, which is why the reader decodes rather than
    // slicing: a raw slice would put six literal characters on her screen.
    const record = '{type:"local",name:"goal",supportsNonInteractive:!0,'
      + 'description:"Set a goal \\u2014 keep working until the condition is met",'
      + 'get isHidden(){return!It()},isEnabled:()=>It()||Ll()}';
    expect(commandFrom('goal', record)).toEqual({
      name: 'goal',
      description: 'Set a goal — keep working until the condition is met',
      menuDescription: null,
      whole: true,
      argumentHint: null,
      aliases: [],
    });
  });

  it('marks a description it had to shorten, so nothing quotes it', () => {
    // /fast is the one of the eight whose description is composed at run time:
    // `get description{return`Toggle fast mode (${cqt})`}`. Cut at the
    // interpolation, and flagged, because a shortened sentence presented as a
    // quotation is the overclaim modes.ts spent a whole round learning not to
    // make.
    const record = '{type:"local",name:"fast",supportsNonInteractive:!0,'
      + 'get description(){return`Toggle fast mode (${cqt()})`},argumentHint:"[on|off]"}';
    const fast = commandFrom('fast', record);
    expect(fast.description).toBe('Toggle fast mode');
    expect(fast.whole).toBe(false);
    expect(CLAUDE_COMMANDS.find((c) => c.name === 'fast').whole).toBe(false);
    // And every other one of the eight IS their whole sentence.
    for (const cmd of CLAUDE_COMMANDS) if (cmd.name !== 'fast') expect(cmd.whole).toBe(true);
  });

  it('prefers their own shorter sentence where they wrote one for a menu', () => {
    // Ours is a menu.
    const usage = CLAUDE_COMMANDS.find((c) => c.name === 'usage');
    expect(usage.menuDescription).toBe('Show session cost and plan usage');
    expect(commandHint(usage)).toBe('Show session cost and plan usage');
    // And a command with no shorter line prints their full one rather than a
    // blank.
    const ctx = CLAUDE_COMMANDS.find((c) => c.name === 'context');
    expect(commandHint(ctx)).toBe(ctx.description);
  });

  it('keeps their aliases, so /cost reaches /usage', () => {
    expect(commandWords(CLAUDE_COMMANDS.find((c) => c.name === 'usage'))).toEqual(['usage', 'cost', 'stats']);
  });

  it('writes a module rather than JSON, so both sides import it the same way', () => {
    // main is node ESM and the renderer is vite. A .json needs an import
    // assertion in one and a plugin in the other; a .mjs needs neither.
    const text = moduleText({ readFrom: '9.9.9', readAt: '2026-01-01', commands: [] });
    expect(text).toContain('export const CLAUDE_COMMANDS = []');
    expect(text).toContain('export const READ_FROM = "9.9.9"');
  });
});

/**
 * THE RULES BELOW ARE ABOUT WHAT IS DRAWN, so the comments have to come out
 *  first. Every one of these assertions failed on its own explanation the first
 *  time it ran: a note saying `.slash-head` was deleted reads, to a substring
 *  search, exactly like `.slash-head` still being there. */
const uncommented = (css) => css.replace(/\/\*[\s\S]*?\*\//g, '');

describe('the menu is one list', () => {
  // The third argument is whether this row reaches Claude Code, and everything
  // in this describe is about the row that does. The Codex row is its own file,
  // tests/the-slash-menu-offers-nothing-codex-cannot-run.test.mjs.
  const rows = (q, set = false, claudeCode = true) => slashRows(q, set, claudeCode);

  it('puts the six modes at the top, which is her word for it', () => {
    const all = rows('');
    expect(all.slice(0, MODE_ORDER.length).every((r) => r.kind === 'mode')).toBe(true);
    expect(all.slice(MODE_ORDER.length).every((r) => r.kind === 'command')).toBe(true);
    expect(all).toHaveLength(MODE_ORDER.length + providerCommands('claude-code').length);
  });

  it('keeps the modes first on a narrowed query too, not only on the empty one', () => {
    // `/c` matches no mode and three commands; `/m` matches Manual and two
    // commands. The order has to be the same shape either way or the cursor
    // lands somewhere different depending on what was typed.
    const m = rows('m');
    expect(m[0]).toEqual({ kind: 'mode', mode: 'default' });
    expect(m.filter((r) => r.kind === 'command').map((r) => r.cmd.name)).toEqual(['model', 'mcp']);
  });

  it('draws nothing at all for a query nobody matches', () => {
    expect(rows('zzz')).toEqual([]);
  });

  it('gives every row a key of its own, so React cannot pair two of them', () => {
    const keys = rows('').map(rowKey);
    expect(new Set(keys).size).toBe(keys.length);
  });

  it('draws one list, with no heading over either half', () => {
    const focus = uncommented(read('renderer/src/components/Focus.tsx'));
    expect(focus).not.toContain('COMMANDS_TITLE');
    expect(focus).not.toContain('slash-head');
    expect(focus).not.toContain('slash-group');
    const css = uncommented(read('renderer/src/styles.css'));
    expect(css).not.toContain('.slash-head');
    expect(css).not.toContain('.slash-group');
    expect(css).not.toContain('.slash-label');
  });

  it('says the same two things on every row, whichever kind it is', () => {
    // THE FLAT LIST IS THIS, not merely the deleted headings. A mode row used
    // to carry a third column, its name, which four times out of six was the
    // command word in title case; a command row never had one. One list cannot
    // be drawn out of two row shapes.
    for (const row of rows('')) {
      const { typed, says } = rowSays(row);
      expect(typed.startsWith('/')).toBe(true);
      expect(says.length).toBeGreaterThan(0);
      expect(Object.keys(rowSays(row))).toEqual(['typed', 'says']);
    }
    expect(rowSays({ kind: 'mode', mode: 'plan' })).toEqual({ typed: '/plan', says: MODE_HINT.plan });
    expect(rowSays({ kind: 'mode', mode: null }).typed).toBe('/clear');
    expect(rowSays({ kind: 'command', cmd: { name: 'model', description: 'Set the AI model' } }))
      .toEqual({ typed: '/model', says: 'Set the AI model' });
  });

  it('lines the sentences up in one column instead of guessing a width', () => {
    // `/plan` is five characters and `/bypass-permissions` is nineteen. Under
    // the old fixed `min-width: 62px` the second column started in six
    // different places down one list, which is what "a little ugly" was.
    const css = uncommented(read('renderer/src/styles.css'));
    const menu = css.slice(css.indexOf('.slash-menu {'), css.indexOf('.slash-row.cursor .slash-hint'));
    expect(menu).toContain('grid-template-columns: max-content 1fr');
    expect(menu).toContain('grid-template-columns: subgrid');
    expect(menu).not.toContain('min-width: 62px');
    expect(menu).not.toContain('text-align: right');
  });

  it('runs a command on Enter and empties the box on a mode', () => {
    // THE MEASUREMENT, ENFORCED. A command eats the message it is attached to,
    // so it cannot be a value carried on her reply the way a mode is; it has to
    // become the reply.
    //
    // AND ENTER SENDS THAT REPLY. The bug was real on every one of the eight.
    // Measured in the running app before the change: Enter left `/usage ` in
    // the box, closed the menu and sent NOTHING, and only Cmd+Enter ever sent.
    // So the one key anybody presses on a highlighted row did nothing visible.
    const focus = read('renderer/src/components/Focus.tsx');
    // Both mode kinds take the same branch: a mode is a value, not a message,
    // whichever engine's vocabulary it belongs to.
    expect(focus).toContain("if (row.kind === 'mode' || row.kind === 'codexMode') { pickMode(row.mode); return; }");
    expect(focus).toContain('send(`/${row.cmd.name}`);');
  });

  it('still completes a command into the box on Tab, for the ones that take an argument', () => {
    // The old reasoning for filling the box was real: half of the eight take an
    // argument. It is Tab's job now rather than Enter's, which is Claude Code's
    // own division of the same two keys.
    expect(commandDraft({ name: 'model' })).toBe('/model ');
    const focus = read('renderer/src/components/Focus.tsx');
    expect(focus).toContain("if (how === 'fill') { setText(commandDraft(row.cmd)); ref.current?.focus(); return; }");
    expect(focus).toContain("pickRow(menuRows[slashAt] ?? menuRows[0], e.key === 'Tab' ? 'fill' : 'run');");
  });

  it('sends the command itself rather than whatever the box held a render ago', () => {
    // `setText` is a state write React has not applied by the time the send
    // runs, so a `send` that read `text` would send the box as it stood
    // BEFORE the pick. The words are handed in instead. This is the whole of
    // why `send` grew an argument, and it fails silently if anybody takes it
    // away again: the reply would go out empty or stale.
    const focus = read('renderer/src/components/Focus.tsx');
    expect(focus).toContain('const send = async (spoken?: string) => {');
    expect(focus).toContain('const words = (spoken ?? text).trim();');
  });
});

describe('what actually reaches the CLI', () => {
  it('recognises each of the eight, by their name and by their aliases', () => {
    for (const cmd of CLAUDE_COMMANDS) {
      for (const word of commandWords(cmd)) {
        // Normalised to the command's own name: an alias is a spelling for us,
        // and sending Claude Code its own word is one less thing to be wrong
        // about.
        expect(commandPrompt(`/${word}`)).toBe(`/${cmd.name}`);
      }
    }
  });

  it('carries the argument through untouched, newlines and all', () => {
    expect(commandPrompt('/model opus')).toBe('/model opus');
    expect(commandPrompt('/goal until the tests are green')).toBe('/goal until the tests are green');
    expect(commandPrompt('/compact keep the\nbits about the parser')).toBe('/compact keep the\nbits about the parser');
  });

  it('is null for everything that is not one of the eight', () => {
    // This is the guard on the brief. A message that loses its brief is a
    // worker that does not know which row it is on, so anything short of an
    // exact match is an ordinary message.
    expect(commandPrompt('/plan')).toBe(null);           // a mode, handled elsewhere
    expect(commandPrompt('/clear')).toBe(null);          // ours, the way back from a mode
    expect(commandPrompt('/theme')).toBe(null);          // real, and not on the menu
    expect(commandPrompt('/modelling is fun')).toBe(null);
    expect(commandPrompt('look at src/model for the fix')).toBe(null);
    expect(commandPrompt(' /context')).toBe(null);       // a slash mid-message is a character
    expect(commandPrompt('')).toBe(null);
    expect(commandPrompt(null)).toBe(null);
    expect(commandPrompt(undefined)).toBe(null);
    expect(commandPrompt(42)).toBe(null);
  });

  it('only replaces the prompt when her own words caused the spawn', () => {
    const sup = read('main/supervisor.mjs');
    // `continuation` is the supervisor's own word for "the user wrote on this
    // row and no worker has answered yet". Without it, `item.answer` sits on the
    // row for good and an ordinary wake hours later would run /context instead
    // of the work.
    // AND ON THE ENGINE, since 2026-09-04. The eight are Claude Code's own
    // words, and on a Codex row the prompt is not argv at all — it is a turn's
    // `input` — so one of the eight would arrive as her message with the brief
    // thrown away. The cases are in the file named at the top of this one.
    expect(sup).toContain('const command = continuation && engine === DEFAULT_ENGINE ? commandPrompt(item.answer, this._nativeCommands?.[item.id]) : review ? item.answer.trim() : null;');
    expect(sup).toContain('if (command) prompt = command;');
  });

  it('settles the delivery on a command run, so she is not shown it three times', () => {
    // A command run answers in the thread and writes nothing on the row, which
    // is exactly what settleDelivery's ordinary test looks for. Left alone it
    // would redeliver to the retry cap.
    const sup = read('main/supervisor.mjs');
    // `carried` is the user's newest word the session really received: the one
    // it was spawned for, or a later one typed into it while it was running
    // (a-reply-typed-into-a-working-agent-comes-back-to-her).
    expect(sup).toContain('const finished = ranClean && (command || this.spokeOnTheRow(item, carried));');
    expect(sup).toContain('{ command: !!plan.command }');
  });
});

/*
 * THE ARGV ITSELF, BUILT BY THE REAL spawnPlan (the pattern is the one
   what-one-reply-may-do.test.mjs established, for the same reason: the round
   before it shipped a control that did nothing, because every piece was right
   and nothing joined them up). */
describe('the command reaches the command line, and nothing else does', () => {
  let appDir;
  let storeRoot;
  const productDir = (slug) => path.join(storeRoot, slug);
  const acme = () => ({ slug: 'acme', name: 'Acme', dir: productDir('acme'), repoPath: null });
  const row = (over = {}) => ({ id: 'w-1', product: 'acme', title: 'do the thing', ...over });

  const supervisor = (over = {}) => {
    const s = Object.create(Supervisor.prototype);
    s.appDir = appDir;
    s.dataDir = appDir;
    // Her own folder, which the app keeps outside the checkout (w-3dc46f3a67).
    s.userDir = appDir;
    s.config = { sessionArgs: ['--permission-mode', 'auto'], personalSessionArgs: [], personalProducts: [] };
    s._personalSessions = {};
    s.buildBrief = () => 'THE BRIEF';
    s.resumeBrief = () => 'THE RESUME BRIEF';
    s.store = { listProducts: () => [acme()] };
    return Object.assign(s, over);
  };

  beforeEach(() => {
    appDir = fs.mkdtempSync(path.join(os.tmpdir(), 'zero-slashcmd-'));
    storeRoot = fs.mkdtempSync(path.join(os.tmpdir(), 'zero-slashcmd-store-'));
    fs.mkdirSync(productDir('acme'), { recursive: true });
  });
  afterEach(() => {
    fs.rmSync(appDir, { recursive: true, force: true });
    fs.rmSync(storeRoot, { recursive: true, force: true });
  });

  const promptOf = (args) => args[args.indexOf('-p') + 1];

  it('sends the command as the whole prompt, with no brief around it', () => {
    // The brief would be discarded by Claude Code anyway (the 142-line
    // measurement at the top of this file). Sending it would only mean paying
    // for it and believing it had been read.
    const { args, command } = supervisor().spawnPlan(
      row({ answer: '/context' }), acme(), { continuation: true },
    );
    expect(command).toBe(true);
    expect(promptOf(args)).toBe('/context');
    expect(args.join(' ')).not.toContain('THE BRIEF');
  });

  it('leaves an ordinary reply with its brief', () => {
    const { args, command } = supervisor().spawnPlan(
      row({ answer: 'yes, ship it' }), acme(), { continuation: true },
    );
    expect(command).toBe(false);
    expect(promptOf(args)).toBe('THE BRIEF');
  });

  it('will not run a command off a row she wrote on hours ago', () => {
    // Not a continuation means this spawn is not because of the user's words.
    // An answer sits on a row for good, so without this an ordinary wake would run
    // /context in place of the work, every time, forever.
    const { args, command } = supervisor().spawnPlan(row({ answer: '/context' }), acme());
    expect(command).toBe(false);
    expect(promptOf(args)).toBe('THE BRIEF');
  });

  it('keeps her own grants on the run, exactly as an ordinary reply would', () => {
    // A command run is still a session on her Mac. It gets the permission mode
    // the project is set to, not a wider one and not a narrower one.
    const { args } = supervisor().spawnPlan(
      row({ answer: '/usage' }), acme(), { continuation: true },
    );
    expect(args.join(' ')).toContain('--permission-mode auto');
    expect(args).toContain('--output-format');
    expect(args).toContain('stream-json');
  });
});

describe('the collision that already exists, named rather than left to be found', () => {
  it('/clear is ours and is not one of the eight', () => {
    // Claude Code HAS a /clear and it means "start a new session with empty
    // context". Ours means "go back to the project's permission setting", and
    // it is a mode row rather than a command row. Two different things under
    // one word, and it predates this work by a day (2026-08-26, modes.ts).
    //
    // NOT CHANGED HERE, deliberately: it is a product decision, and taking a
    // word off the menu without asking is the kind of thing rule six of the project
    // instructions is about. This test only pins the fact so the next session
    // finds it stated instead of discovering it.
    expect(commandMatches('clear')).toEqual([]);
    expect(WANTED).not.toContain('clear');
  });
});
