// MP-03: previews executed zero commands. Real terminals must keep exactly one
// shell per task, preserve input literally, bound retained output, and never
// SILENTLY substitute a different folder when a task's checkout disappears.
// Since w-566a2e749f a merged task's missing checkout opens the project folder
// and the shell's first line says so; with no folder at all it still refuses.
import {it,expect,vi} from 'vitest';
import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {TaskTerminals,terminalFolder,terminalPlace,terminalEnv} from '../main/task-terminals.mjs';
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'terminal cases '));
function fixture(){let data,exit;const child={pid:999999,write:vi.fn(),resize:vi.fn(),kill:vi.fn(),onData:f=>data=f,onExit:f=>exit=f};const spawn=vi.fn(()=>child);return {manager:new TaskTerminals({spawn,resolve:()=>dir,disposeProcess:p=>p.kill()}),spawn,child,output:s=>data(s),exit:()=>exit({exitCode:2})};}
it('opens once, preserves literal input and isolates another task',()=>{const f=fixture();f.manager.open('p:a');f.manager.open('p:a');expect(f.spawn).toHaveBeenCalledTimes(1);f.manager.write('p:a','printf "C:\\folder"\n');expect(f.child.write).toHaveBeenCalledWith('printf "C:\\folder"\n');expect(()=>f.manager.write('p:b','bad')).toThrow();});
it('retains output across reads and explicitly marks trimmed output',()=>{const f=fixture();f.manager.open('p:a');f.output('abc');expect(f.manager.read('p:a',0).data).toBe('abc');expect(f.manager.read('p:a',3).data).toBe('');f.output('x'.repeat(300000));const read=f.manager.read('p:a',0);expect(read.truncated).toBe(true);expect(read.data.length).toBeLessThanOrEqual(262144);});
it('validates resize and input, reports exit, and requires explicit restart',()=>{const f=fixture();f.manager.open('p:a');expect(()=>f.manager.resize('p:a',0,12)).toThrow();f.manager.resize('p:a',80,24);expect(f.child.resize).toHaveBeenCalledWith(80,24);expect(()=>f.manager.write('p:a','x'.repeat(70000))).toThrow();f.exit();expect(f.manager.read('p:a',0).exitCode).toBe(2);expect(()=>f.manager.write('p:a','no')).toThrow();f.manager.open('p:a');expect(f.spawn).toHaveBeenCalledTimes(1);f.manager.close('p:a');f.manager.open('p:a');expect(f.spawn).toHaveBeenCalledTimes(2);f.manager.dispose();expect(f.child.kill).toHaveBeenCalled();});
it('resolves recorded task checkout before project root and refuses missing checkout',()=>{const store={listItems:()=>[{id:'a',product:'p'}],listProducts:()=>[{slug:'p',repoPath:dir,dir:'/fallback'}]};expect(terminalFolder({store,supervisor:{_rowSessions:{a:{product:'p',cwd:dir}}},product:'p',id:'a'})).toBe(dir);expect(()=>terminalFolder({store,supervisor:{},product:'wrong',id:'a'})).toThrow();});
it('opens the project folder, and says so, once the task checkout was merged away',()=>{const task=fs.mkdtempSync(path.join(os.tmpdir(),'task checkout '));const store={listItems:()=>[{id:'a',product:'p'}],listProducts:()=>[{slug:'p',repoPath:dir,dir:'/fallback'}]};const supervisor={_rowSessions:{a:{product:'p',cwd:task}}};expect(terminalPlace({store,supervisor,product:'p',id:'a'})).toEqual({cwd:task,notice:undefined});fs.rmSync(task,{recursive:true});const moved=terminalPlace({store,supervisor,product:'p',id:'a'});expect(moved.cwd).toBe(dir);expect(moved.notice).toContain('project folder');const gone={listItems:store.listItems,listProducts:()=>[{slug:'p',repoPath:'/missing-repo',dir:'/missing-dir'}]};expect(()=>terminalFolder({store:gone,supervisor,product:'p',id:'a'})).toThrow('working folder is unavailable');});
it('prints the fallback notice as the shell first line',()=>{const f=fixture();const m=new TaskTerminals({spawn:()=>f.child,resolve:()=>({cwd:dir,notice:'Opened in the project folder.'}),disposeProcess:p=>p.kill()});const r=m.open('p:a');expect(r.cwd).toBe(dir);expect(r.data).toContain('Opened in the project folder.');m.dispose();});
it('does not inherit API billing overrides or nested-agent markers',()=>{const env=terminalEnv({PATH:'/bin',HOME:dir,ANTHROPIC_API_KEY:'no',OPENAI_API_KEY:'no',CLAUDECODE:'1',ELECTRON_RUN_AS_NODE:'1'});expect(env.HOME).toBe(dir);expect(env.ANTHROPIC_API_KEY).toBeUndefined();expect(env.OPENAI_API_KEY).toBeUndefined();expect(env.CLAUDECODE).toBeUndefined();expect(env.ELECTRON_RUN_AS_NODE).toBeUndefined();});
it('never signals an already exited shell PID that the OS could have reused',()=>{const f=fixture();f.manager.open('p:a');f.exit();f.manager.close('p:a');expect(f.child.kill).not.toHaveBeenCalled();});
it('refuses a missing shell without retaining a broken session',()=>{const m=new TaskTerminals({resolve:()=>dir,spawn:()=>{throw Error('shell missing');}});expect(()=>m.open('p:a')).toThrow('shell missing');expect(m.sessions.size).toBe(0);});
// THE CAP NOW REUSES BEFORE IT REFUSES. This used to assert that the 21st
// terminal THREW. It does not any more: the least recently watched idle shell
// makes room, because the old sentence told her to end a session and ending
// sessions is the one thing she has said she never does. The refusal survives
// for the state where it is still true, which is twenty shells all running
// something; tests/shells-end-themselves.test.mjs carries that case and the
// rest of the rule.
it('reuses the oldest idle slot at the cap and still reconnects to an open shell',()=>{const f=fixture();for(let i=0;i<20;i++)f.manager.open('p:'+i);expect(()=>f.manager.open('p:20')).not.toThrow();expect(f.manager.sessions.size).toBe(20);expect(f.manager.sessions.has('p:0')).toBe(false);expect(()=>f.manager.open('p:1')).not.toThrow();f.manager.dispose();});
it('waits for native exit callbacks before allowing Electron to quit',async()=>{const f=fixture();f.manager.open('p:a');let finished=false;const done=f.manager.shutdown().then(()=>finished=true);await Promise.resolve();expect(finished).toBe(false);f.exit();await done;expect(finished).toBe(true);});
