// GENERATED BY scripts/read-claude-models.mjs. DO NOT EDIT BY HAND.

export declare const READ_FROM: string | null;
export declare const READ_AT: string;

export declare const CLAUDE_MODELS: ReadonlyArray<{
  /** What Agentbox sends the CLI: an alias, never a version. */
  alias: string;
  /** What that alias resolved to on the Claude Code that built this. */
  id: string;
  /** Claude Code's own display name for that id, e.g. "Opus 5". */
  label: string;
  /** The level it thinks at when nobody picks one, out of the same catalog. */
  defaultLevel: string | null;
}>;
